chat: # 聊天设置
  model: qwen # qwen:0.5b qwen:1.8b qwen:4b qwen:8b gemma gemma:7b mistral (https://ollama.com/library)
  max_history: 10 # 最大历史记录数
  system_prompt: 你是AI助手，你要尽力回答用户提出的任何问题。

lark: # 飞书
  app_id: 
  app_secret:
  verification_token:
  encrypt_key:
